# Docker Compose for Discord Election Bot

version: '3.8'

services:
  discord-bot:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    volumes:
      # Mount a volume for persistent local data if needed
      - bot_data:/app/data
    # Uncomment for health checks
    # healthcheck:
    #   test: ["CMD", "node", "-e", "console.log('health check')"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

volumes:
  bot_data:
    driver: local
